#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# GeoP phase2 fine-tune on LIBERO (4 suites, with observation.keypoint_3d)
#
# Data (generated by util_scripts/generate_libero_keypoints.py, then converted to LeRobot v3.0):
#   /home/a26160/DATA/LIBERO/libero_kpt_v30/libero_*_no_noops_1.0.0_lerobot
#   HF_LEROBOT_HOME=/home/a26160/DATA/LIBERO
#   repo_id = libero_kpt_v30/<suite_dir>
#
# Recipe (aligned with stackb3 GeoP phase2):
#   - Action + Kpt losses (action=10, kpt=0.1, kpt_fut=0.1)
#   - train_expert_only=true, enable_vqa_loss=false
#   - WAN loaded/frozen, video_loss_weight=0.0
#   - num_keypoint_joints=8 (Franka single-arm; NOT 14 from aloha)
#
# Default pretrained is InternVLA-A1.5-base (J=8 GeoP modules init fresh).
# Do NOT load a J=14 stackb3 GeoP ckpt unless you also set NUM_KPT_JOINTS=14
# (shape mismatch otherwise).
#
# Usage:
#   bash launch/internvla_a15_geop_phase2_finetune_libero.sh
#   STEPS=100 BATCH_SIZE=4 PROC_PER_NODE=2 CUDA_VISIBLE_DEVICES=0,1 \
#     bash launch/internvla_a15_geop_phase2_finetune_libero.sh
#   PRETRAINED_PATH=/path/to/ckpt bash launch/internvla_a15_geop_phase2_finetune_libero.sh
###############################################################################

export HF_HOME="${HF_HOME:-${HOME}/.cache/huggingface}"
export HF_LEROBOT_HOME="${HF_LEROBOT_HOME:-/home/a26160/DATA/LIBERO}"
# `datasets` takes a FileLock per Dataset.from_parquet call. ${HOME} is a fuse
# network mount here, where 8 concurrent ranks trip "OSError: [Errno 116] Stale
# file handle" on the lock. Keep that cache (locks included) on local disk.
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-/tmp/hf_datasets_cache}"
mkdir -p "${HF_DATASETS_CACHE}"
# tilelang JIT-compiles the fla gated-delta-rule kernels; keep that cache off the
# fuse mount too, since all ranks write it concurrently on a cold cache.
export TILELANG_CACHE_DIR="${TILELANG_CACHE_DIR:-/tmp/tilelang_cache}"
mkdir -p "${TILELANG_CACHE_DIR}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export USE_LIBUV="${USE_LIBUV:-0}"
export PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export TOKENIZERS_PARALLELISM=false

CONDA_ROOT="${CONDA_ROOT:-${_CONDA_ROOT:-/opt/conda}}"
CONDA_ENV="${CONDA_ENV:-internvla_a1_5}"
# Prefer explicit PYTHON if set; otherwise conda env.
if [[ -z "${PYTHON:-}" ]]; then
  if [[ -x "${CONDA_ROOT}/envs/${CONDA_ENV}/bin/python" ]]; then
    # shellcheck source=/dev/null
    source "${CONDA_ROOT}/etc/profile.d/conda.sh"
    conda activate "${CONDA_ENV}"
    PYTHON="$(command -v python)"
  else
    PYTHON="$(command -v python)"
  fi
fi
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:${CONDA_PREFIX:-}/lib:${LD_LIBRARY_PATH:-}"

export MASTER_ADDR="${MASTER_ADDR:-127.0.0.1}"
export MASTER_PORT="${MASTER_PORT:-36523}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
PROC_PER_NODE="${PROC_PER_NODE:-8}"
NODE_COUNT="${NODE_COUNT:-1}"
NODE_RANK="${NODE_RANK:-0}"
NUM_PROCESSES=$((NODE_COUNT * PROC_PER_NODE))

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJ_ROOT}"

# data/ -> HF_LEROBOT_HOME so robot_type patch and LeRobot loaders resolve consistently.
if [[ ! -e "${PROJ_ROOT}/data" ]]; then
  ln -sfn "${HF_LEROBOT_HOME}" "${PROJ_ROOT}/data"
  echo "[link] data -> ${HF_LEROBOT_HOME}"
elif [[ -L "${PROJ_ROOT}/data" ]]; then
  echo "[link] data already -> $(readlink -f "${PROJ_ROOT}/data")"
fi

POLICY="internvla_a1_5"
# Local directory rather than the hub repo id: hf_hub_download's lock lives on the
# fuse mount and 8 concurrent ranks trip "OSError: [Errno 116] Stale file handle".
PRETRAINED_PATH="${PRETRAINED_PATH:-/home/a26160/CKPT/InternVLA-A1.5-base}"
VLM_MODEL_PATH="${VLM_MODEL_PATH:-/home/a26160/CKPT/Qwen3.5-2B}"
WAN_DIR="${WAN_DIR:-/home/a26160/CKPT/Wan2.2-TI2V-5B}"
NUM_KPT_JOINTS="${NUM_KPT_JOINTS:-8}"
# torchcodec 0.15 in this env is a CUDA-13 build (torch here is cu128) and only
# ships FFmpeg 4-8 cores against the installed FFmpeg 9. Every decode then falls
# back to zero-filled frames, which silently destroys training.
VIDEO_BACKEND="${VIDEO_BACKEND:-pyav}"

if [[ ! -f "${PRETRAINED_PATH}/model.safetensors" ]]; then
  echo "ERROR: ${PRETRAINED_PATH}/model.safetensors missing." >&2
  echo "Fetch it once (single process), then re-run:" >&2
  echo "  hf download InternRobotics/InternVLA-A1.5-base model.safetensors \\" >&2
  echo "    --local-dir ${PRETRAINED_PATH}" >&2
  exit 1
fi

LIBERO_KPT_ROOT="${LIBERO_KPT_ROOT:-${HF_LEROBOT_HOME}/libero_kpt_v30}"
DATASET_REPO_ID="$(
  find -L "${LIBERO_KPT_ROOT}" -mindepth 1 -maxdepth 1 -type d -name "libero_*_no_noops*_lerobot" 2>/dev/null \
  | while read -r d; do
      if [[ -d "${d}/meta" && ( -d "${d}/videos" || -L "${d}/videos" ) ]]; then
        # HF_LEROBOT_HOME / repo_id == suite path (LeRobot v3.0)
        echo "libero_kpt_v30/$(basename "${d}")"
      fi
    done \
  | sort -u \
  | tr '\n' ' ' | xargs
)"
if [[ -z "${DATASET_REPO_ID}" ]]; then
  echo "ERROR: no libero_kpt_v30 suites under ${LIBERO_KPT_ROOT}" >&2
  echo "Convert v2.1 kpt data first, e.g.:" >&2
  echo "  HF_LEROBOT_HOME=${HF_LEROBOT_HOME} python src/lerobot/datasets/v30/convert_my_dataset_v21_to_v30.py \\" >&2
  echo "    --old-repo-id libero_kpt/<suite> --new-repo-id libero_kpt_v30/<suite> --push-to-hub false" >&2
  exit 1
fi
echo "DATASET_REPO_ID=${DATASET_REPO_ID}"

ACTION_TYPE=abs
USE_EXTERNAL_STATS=false

# Per-suite robot_type so aggregated stats do not collide.
if [[ "${NODE_RANK}" = "0" ]]; then
  for repo in ${DATASET_REPO_ID}; do
    info_json="data/${repo}/meta/info.json"
    subset_robot_type="$(basename "${repo}")"
    subset_robot_type="${subset_robot_type%%_no_noops*}"  # libero_10 / libero_goal / ...
    if [[ -f "${info_json}" ]]; then
      "${PYTHON}" -c "
import json
p = '${info_json}'
target = '${subset_robot_type}'
with open(p) as f:
    d = json.load(f)
if d.get('robot_type') != target:
    d['robot_type'] = target
    with open(p, 'w') as f:
        json.dump(d, f, indent=4)
    print(f'[info-patch] robot_type -> {target} in {p}')
else:
    print(f'[info-patch] already {target} in {p}')
"
    else
      echo "[info-patch] WARNING: ${info_json} not found"
    fi
  done
fi

BATCH_SIZE="${BATCH_SIZE:-16}"
STEPS="${STEPS:-100000}"
SAVE_FREQ="${SAVE_FREQ:-5000}"
LOG_FREQ="${LOG_FREQ:-50}"
NUM_WORKERS="${NUM_WORKERS:-8}"

JOB_NAME="${JOB_NAME:-$(date +'%Y_%m_%d_%H_%M_%S')-${POLICY}-geop-phase2-libero-abs-j${NUM_KPT_JOINTS}}"
OUTPUT_DIR="${OUTPUT_DIR:-${PROJ_ROOT}/outputs/${POLICY}/${JOB_NAME}}"

echo "PYTHON=${PYTHON}"
echo "PRETRAINED_PATH=${PRETRAINED_PATH}"
echo "VLM_MODEL_PATH=${VLM_MODEL_PATH}"
echo "WAN_DIR=${WAN_DIR} (loaded, frozen, no video loss)"
echo "HF_LEROBOT_HOME=${HF_LEROBOT_HOME}"
echo "VIDEO_BACKEND=${VIDEO_BACKEND}"
echo "NUM_KPT_JOINTS=${NUM_KPT_JOINTS}"
echo "OUTPUT_DIR=${OUTPUT_DIR}"
echo "loss: action=10 kpt=0.1 kpt_fut=0.1 | no vlm, no video"

ARGS=()
if (( NUM_PROCESSES > 1 )); then
  ARGS+=(--multi_gpu)
fi
ARGS+=(
  --num_processes="${NUM_PROCESSES}"
  --num_machines="${NODE_COUNT}"
  --machine_rank="${NODE_RANK}"
  --main_process_ip="${MASTER_ADDR}"
  --main_process_port="${MASTER_PORT}"
  src/lerobot/scripts/lerobot_train.py

  --output_dir="${OUTPUT_DIR}"
  --num_workers="${NUM_WORKERS}"
  --job_name="${JOB_NAME}"

  --policy.type=${POLICY}
  --policy.repo_id=lerobot_lab/${POLICY}
  --policy.push_to_hub=false
  --policy.pretrained_path="${PRETRAINED_PATH}"
  --policy.gradient_checkpointing=false
  --policy.dtype=bfloat16
  --policy.optimizer_lr=5e-5
  --policy.scheduler_warmup_steps=2000
  --policy.scheduler_decay_steps=${STEPS}
  --policy.scheduler_decay_lr=5e-6
  --policy.freeze_vision_encoder=false
  --policy.train_expert_only=true
  --policy.vlm_model_name_or_path="${VLM_MODEL_PATH}"
  --policy.enable_vqa_loss=false
  --policy.tokenize_state=true
  --policy.video_loss_only=false
  --policy.video_loss_weight=0.0
  --policy.freeze_learnable_tokens=false
  --policy.num_learnable_tokens=50
  --policy.wan_checkpoint_path="${WAN_DIR}"
  --policy.wan_config_path="${WAN_DIR}"
  --policy.vae_path="${WAN_DIR}/Wan2.2_VAE.pth"

  # ---- GeoP (Franka J=8) ----
  --policy.enable_keypoint_predictor=true
  --policy.num_keypoint_joints=${NUM_KPT_JOINTS}
  --policy.action_loss_weight=10.0
  --policy.kpt_loss_weight=0.1
  --policy.kpt_future_loss_weight=0.1
  --policy.kpt_to_action_detach=false
  --policy.knowledge_insulation=true
  --policy.knowledge_insulation_kpt=true
  --policy.ki_gradient_scale=0.0
  --policy.ki_kpt_gradient_scale=0.0
  --policy.freeze_keypoint_modules=false
  --policy.action_expert_lr_scale=1.0
  --policy.kpt_expert_lr_scale=1.0
  --policy.track_encoder_lr_scale=1.0
  --policy.init_kpt_expert_from_action=false
  --policy.action_loss_only=false

  # ---- Dataset (LIBERO kpt) ----
  --dataset.type=${POLICY}
  --dataset.repo_id="${DATASET_REPO_ID}"
  --dataset.enable_keypoint_predictor=true
  --dataset.num_keypoint_joints=${NUM_KPT_JOINTS}
  --dataset.vlm_model_name_or_path="${VLM_MODEL_PATH}"
  --dataset.video_backend="${VIDEO_BACKEND}"
  --dataset.action_mode=${ACTION_TYPE}
  --dataset.use_external_stats=${USE_EXTERNAL_STATS}
  --dataset.dist_loading=false
  --dataset.tokenize_state=true
  --dataset.use_fast_action_tokens=false

  --seed=42
  --batch_size=${BATCH_SIZE}
  --steps=${STEPS}
  --save_freq=${SAVE_FREQ}
  --log_freq=${LOG_FREQ}

  --wandb.enable=true
  --wandb.project=${POLICY}
  --wandb.mode=offline
)

set +e
"${PYTHON}" -m accelerate.commands.launch "${ARGS[@]}"
TRAIN_EXIT=$?
set -e
exit "${TRAIN_EXIT}"
