#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Phase 1 GeoP Warmup — LIBERO 4-suite, 8×7D keypoints (kpt_4d_mode=pos_rot)
#
# Trains kpt expert + action expert from InternVLA-A1.5-base + GeoPredict,
# with VLM frozen. Requires datasets with observation.keypoint_3d generated by
# util_scripts/generate_libero_keypoints.py and split via split_libero_merged.py.
#
# Usage:
#   bash launch/internvla_a15_geop_phase1_libero_warmup.sh
#   SMOKE=1 bash launch/internvla_a15_geop_phase1_libero_warmup.sh
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_ROOT="${PROJ_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

export HF_HOME="${HF_HOME:-/tmp/zwy}"
export HF_LEROBOT_HOME="${HF_LEROBOT_HOME:-${HF_HOME}/lerobot}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export USE_LIBUV="${USE_LIBUV:-0}"
export PYTHONUNBUFFERED=1
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export TOKENIZERS_PARALLELISM=false
export NCCL_TUNER_PLUGIN="${NCCL_TUNER_PLUGIN:-/dev/null}"

CONDA_ENV="${CONDA_ENV:-internvla_a1_5}"
CONDA_ROOT="${CONDA_ROOT:-/opt/conda}"

if [[ -z "${CONDA_PREFIX:-}" || "$(basename "${CONDA_PREFIX}")" != "${CONDA_ENV}" ]]; then
  if [[ -f "${CONDA_ROOT}/etc/profile.d/conda.sh" ]]; then
    # shellcheck disable=SC1091
    source "${CONDA_ROOT}/etc/profile.d/conda.sh"
    conda activate "${CONDA_ENV}"
  else
    echo "ERROR: ${CONDA_ENV} not active and conda not found at ${CONDA_ROOT}. Run: conda activate ${CONDA_ENV}" >&2
    exit 1
  fi
fi

PYTHON="${PYTHON:-python}"
PY_SITE="${CONDA_PREFIX}/lib/python3.11/site-packages"

export CUDA_HOME="${CUDA_HOME:-/usr/local/cuda-12.8}"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:${CONDA_PREFIX}/lib:\
${PY_SITE}/torch/lib:\
${PY_SITE}/nvidia/cuda_runtime/lib:\
${PY_SITE}/nvidia/cuda_nvrtc/lib:\
${PY_SITE}/nvidia/npp/lib:${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"

export MASTER_ADDR="${MASTER_ADDR:-127.0.0.1}"
export MASTER_PORT="${MASTER_PORT:-36801}"

POLICY="internvla_a1_5"
PRETRAINED_PATH="${PRETRAINED_PATH:-${HF_HOME}/ckpts/InternVLA-A1.5-base}"
GEOPREDICT_CKPT="${GEOPREDICT_CKPT:-${HF_HOME}/ckpts/GeoPredict_robocasa.pth}"
VLM_MODEL_PATH="${VLM_MODEL_PATH:-Qwen/Qwen3.5-2B}"

DATASET_REPO_ID="${DATASET_REPO_ID:-libero_spatial libero_object libero_goal libero_10}"
ACTION_TYPE=abs
USE_EXTERNAL_STATS=false

SMOKE="${SMOKE:-0}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-false}"

if [[ "${SMOKE}" == "1" ]]; then
  export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
  PROC_PER_NODE="${PROC_PER_NODE:-1}"
  BATCH_SIZE="${BATCH_SIZE:-2}"
  STEPS="${STEPS:-100}"
  NUM_WORKERS="${NUM_WORKERS:-2}"
  SAVE_FREQ="${SAVE_FREQ:-100}"
  LOG_FREQ="${LOG_FREQ:-10}"
  SCHED_WARMUP_STEPS="${SCHED_WARMUP_STEPS:-20}"
  WANDB_ENABLE="${WANDB_ENABLE:-false}"
  JOB_SUFFIX="libero-geop-warmup-smoke"
else
  export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
  PROC_PER_NODE="${PROC_PER_NODE:-8}"
  BATCH_SIZE="${BATCH_SIZE:-16}"
  STEPS="${STEPS:-400}"
  NUM_WORKERS="${NUM_WORKERS:-8}"
  SAVE_FREQ="${SAVE_FREQ:-200}"
  LOG_FREQ="${LOG_FREQ:-50}"
  SCHED_WARMUP_STEPS="${SCHED_WARMUP_STEPS:-100}"
  WANDB_ENABLE="${WANDB_ENABLE:-true}"
  JOB_SUFFIX="libero-geop-phase1-warmup"
fi

NODE_COUNT="${NODE_COUNT:-1}"
NODE_RANK="${NODE_RANK:-0}"
NUM_PROCESSES=$((NODE_COUNT * PROC_PER_NODE))
SCHED_DECAY_STEPS="${SCHED_DECAY_STEPS:-${STEPS}}"
SCHED_DECAY_LR="${SCHED_DECAY_LR:-5e-6}"

cd "${PROJ_ROOT}"

JOB_NAME="${JOB_NAME:-$(date +'%Y_%m_%d_%H_%M_%S')-${POLICY}-${JOB_SUFFIX}}"
OUTPUT_DIR="${OUTPUT_DIR:-${PROJ_ROOT}/outputs/${POLICY}/${JOB_NAME}}"
LOG_FILE="${LOG_FILE:-${OUTPUT_DIR}.log}"

echo "=== Phase 1 Warmup: LIBERO GeoP 7D (kpt_4d_mode=pos_rot) ==="
echo "PROJ_ROOT=${PROJ_ROOT}"
echo "HF_HOME=${HF_HOME}"
echo "HF_LEROBOT_HOME=${HF_LEROBOT_HOME}"
echo "PRETRAINED_PATH=${PRETRAINED_PATH}"
echo "GEOPREDICT_CKPT=${GEOPREDICT_CKPT}"
echo "DATASET_REPO_ID=${DATASET_REPO_ID}"
echo "OUTPUT_DIR=${OUTPUT_DIR}"
echo "SMOKE=${SMOKE} PROC=${NUM_PROCESSES} BS=${BATCH_SIZE} STEPS=${STEPS}"
echo "num_keypoint_joints=8, kpt_4d_mode=pos_rot (56D)"

# Idempotent robot_type patch for per-suite stats.
if [[ "${NODE_RANK}" == "0" ]]; then
  for repo in ${DATASET_REPO_ID}; do
    info_json="${HF_LEROBOT_HOME}/${repo}/meta/info.json"
    if [[ -f "${info_json}" ]]; then
      python -c "
import json
p = '${info_json}'
target = '${repo}'
with open(p) as f:
    d = json.load(f)
if d.get('robot_type') != target:
    d['robot_type'] = target
    with open(p, 'w') as f:
        json.dump(d, f, indent=4)
    print(f'[info-patch] robot_type -> {target} in {p}')
"
    else
      echo "[info-patch] WARNING: ${info_json} not found — run setup_libero_geop.sh first"
    fi
  done
fi

mkdir -p "$(dirname "${LOG_FILE}")"

LAUNCH_ARGS=()
if [[ "${NUM_PROCESSES}" -gt 1 ]]; then
  LAUNCH_ARGS+=(--multi_gpu)
fi
LAUNCH_ARGS+=(
  --num_processes="${NUM_PROCESSES}"
  --num_machines="${NODE_COUNT}"
  --machine_rank="${NODE_RANK}"
  --main_process_ip="${MASTER_ADDR}"
  --main_process_port="${MASTER_PORT}"
)

ARGS=(
  "${LAUNCH_ARGS[@]}"
  src/lerobot/scripts/lerobot_train.py
  --output_dir="${OUTPUT_DIR}"
  --job_name="${JOB_NAME}"
  --num_workers="${NUM_WORKERS}"

  --policy.type="${POLICY}"
  --policy.repo_id=lerobot_lab/"${POLICY}"
  --policy.push_to_hub=false
  --policy.pretrained_path="${PRETRAINED_PATH}"
  --policy.gradient_checkpointing="${GRADIENT_CHECKPOINTING}"
  --policy.dtype=bfloat16
  --policy.vlm_model_name_or_path="${VLM_MODEL_PATH}"

  --policy.train_expert_only=true
  --policy.knowledge_insulation=true
  --policy.knowledge_insulation_kpt=true
  --policy.action_loss_only=true
  --policy.video_loss_only=false
  --policy.enable_vqa_loss=false
  --policy.tokenize_state=true
  --policy.freeze_learnable_tokens=true
  --policy.num_learnable_tokens=50

  --policy.enable_keypoint_predictor=true
  --policy.num_keypoint_joints=8
  --policy.kpt_4d_mode=pos_rot
  --policy.keypoint_history_max_len=200
  --policy.init_kpt_expert_from_action=true
  --policy.geopredict_checkpoint_path="${GEOPREDICT_CKPT}"
  --policy.freeze_keypoint_modules=false
  --policy.kpt_to_action_detach=false

  --policy.action_loss_weight=2.0
  --policy.kpt_loss_weight=10.0
  --policy.kpt_future_loss_weight=2.0

  --policy.optimizer_lr=5e-5
  --policy.action_expert_lr_scale=0.04
  --policy.kpt_expert_lr_scale=1.0
  --policy.track_encoder_lr_scale=1.0
  --policy.scheduler_warmup_steps="${SCHED_WARMUP_STEPS}"
  --policy.scheduler_decay_steps="${SCHED_DECAY_STEPS}"
  --policy.scheduler_decay_lr="${SCHED_DECAY_LR}"

  --dataset.type="${POLICY}"
  --dataset.repo_id="${DATASET_REPO_ID}"
  --dataset.enable_keypoint_predictor=true
  --dataset.num_keypoint_joints=8
  --dataset.kpt_4d_mode=pos_rot
  --dataset.keypoint_history_max_len=200
  --dataset.action_mode="${ACTION_TYPE}"
  --dataset.tokenize_state=true
  --dataset.use_fast_action_tokens=true
  --dataset.use_external_stats="${USE_EXTERNAL_STATS}"
  --dataset.dist_loading=false

  --seed=42
  --batch_size="${BATCH_SIZE}"
  --steps="${STEPS}"
  --save_freq="${SAVE_FREQ}"
  --log_freq="${LOG_FREQ}"

  --wandb.enable="${WANDB_ENABLE}"
  --wandb.project="${POLICY}"
  --wandb.mode=offline
)

set -o pipefail
"${PYTHON}" -m accelerate.commands.launch "${ARGS[@]}" 2>&1 | tee "${LOG_FILE}"
train_exit=${PIPESTATUS[0]}

decode_err=$(grep -c '\[video_decode_error\]' "${LOG_FILE}" 2>/dev/null) || decode_err=0
zero_frames=$(grep -c 'using_zeros' "${LOG_FILE}" 2>/dev/null) || zero_frames=0
echo "post_check: video_decode_error=${decode_err} using_zeros=${zero_frames} exit=${train_exit}"
exit "${train_exit}"
